### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by NoahNxT** [Daynnnnn/soketi-ui#3]
Hi!
Not really an issue but I really appreciate this project!

Is there any timeline for you that you could enroll this as a plug in docker image? 

Keep up the good work!

**Comment by Daynnnnn** [comment]
Hey! I've got a rebuild in the works at the moment - I'll sort this as part of that :)

**Comment by compgeniuses** [comment]
hello, any news on this part?

**Comment by Daynnnnn** [comment]
Hey! Just pushed up V2, which has a docker compose file
