### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by hwtdnet** [Daynnnnn/soketi-ui#5]
System: Windows Wsl Docker

Development Environment: Laradock

run ` php artisan migrate ` prompt:

```bash
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'soketi-ui.apps' doesn't exist (SQL: alter table `apps` add `name` varchar(255) null after `secret`)
```

` database/migrations ` not has app table

**Comment by Daynnnnn** [comment]
Hey! You'll wanna create the apps table manually before running migrations, I've done this so we don't need to track schema changes to Soketi:
https://github.com/Daynnnnn/soketi-ui/blob/main/README.md?plain=1#L20-L22
